### ISSUE TITLE
"drag_and_zoom" and "rotate_50m" are  broken

### ISSUE THREAD

**Issue by anuragbakshi** [martinfrances107/rust_d3_geo#19] opened 2023-02-04 21:43 UTC
I get the following errors when trying to build this example:

ERROR in ./index.ts 14:0-89
Module not found: Error: Can't resolve '../pkg/rust_d3_geo_example_globe_drag_and_zoom' in '/Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/www'
resolve '../pkg/rust_d3_geo_example_globe_drag_and_zoom' in '/Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/www'
  using description file: /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/www/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    No description file found in /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/pkg or above
    no extension
      Field 'browser' doesn't contain a valid alias configuration
      /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/pkg/rust_d3_geo_example_globe_drag_and_zoom doesn't exist
    .tsx
      Field 'browser' doesn't contain a valid alias configuration
      /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/pkg/rust_d3_geo_example_globe_drag_and_zoom.tsx doesn't exist
    .ts
      Field 'browser' doesn't contain a valid alias configuration
      /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/pkg/rust_d3_geo_example_globe_drag_and_zoom.ts doesn't exist
    .js
      Field 'browser' doesn't contain a valid alias configuration
      /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/pkg/rust_d3_geo_example_globe_drag_and_zoom.js doesn't exist
    as directory
      /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/pkg/rust_d3_geo_example_globe_drag_and_zoom doesn't exist
 @ ./bootstrap.ts 4:0-17

ERROR in [eslint] No ESLint configuration found in /Users/anuragbakshi/Dropbox/Desktop/rust_d3_geo/examples/globe/drag_and_zoom/www.

webpack 5.75.0 compiled with 2 errors in 654 ms

**Comment by martinfrances107** [comment] 2023-02-05 11:54
Yep, It is a known issues... I am working on this .. 

Just reporting what I see examples/rotating_50m is also broken

**Comment by martinfrances107** [comment] 2023-02-05 21:19
Update, I have just commited a partial fix.

the rotating examples now works again 

```
cd examples/globe/rotating_50m/
npm i
npm run build
npm run serve
```

as does the development mode.
```
cd examples/globe/rotating_50m/
npm i
npm run start
````

I  am still working on drag_and_zoom, but now I have a template for  its restoration

**Comment by martinfrances107** [comment] 2023-02-05 22:09
examples/globe/drag_and_zoom has been restored to a working state.

Both "npm run start" and "npm run serve" work.

When I say working state .. the rotation has glitches and the rotation was "gimbal lock like" problems. 

This is the weakest of the examples... and something I want to go back and fix.

Please let me know if this solves the issues.

**Comment by martinfrances107** [comment] 2023-02-05 22:27
pushed

**Comment by martinfrances107** [comment] 2023-02-16 22:49
I am going to close this, please reopen, if the problem is not fixed at your end.

**Closed by martinfrances107** 2023-02-16 22:49 UTC
